[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#feca57"
backgroundColor = "#1e1e2f"
secondaryBackgroundColor = "#2a2a40"
textColor = "#ffffff"
font = "sans serif"
